# Generated by Django 5.0.7 on 2024-07-29 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('DAY_OF_MONTH', 'Day of Month'), ('SPECIFIC_DATE', 'Specific Date')], max_length=20)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('INSURANCE', 'Insurance'), ('PENSION', 'Pension'), ('FINANCIAL', 'Financial')], max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('terms', models.JSONField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.insurancecompany')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('SCOPE', 'Scope Commission'), ('RECURRING', 'Recurring Commission'), ('RETENTION', 'Retention Bonus'), ('OVERRIDE', 'Override Commission'), ('TRAIL', 'Trail Commission'), ('RENEWAL', 'Renewal Commission')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.agreement')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.paymentterms')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.product')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('processed_status', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTransactionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_schemas', to='commission.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.product')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_payment_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('commission_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.commissionstructure')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.transaction')),
            ],
        ),
    ]
