# Generated by Django 5.0.7 on 2024-08-05 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='commissions',
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commission.agreement'),
        ),
        migrations.AlterField(
            model_name='commissionstructure',
            name='commission_type',
            field=models.CharField(choices=[('SCOPE', 'Scope'), ('RECURRING', 'Recurring')], max_length=20),
        ),
    ]
